### PR TITLE
Updated App Icon

### PR DESCRIPTION
**Pull request by sherryycxie**
# *Name of the PR*

## :recycle: Current situation & Problem
Updated the App Icon to be the one we created together

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [ ] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PSchmiedmayer** [comment]
@sherryycxie Thank you for updating the app icon!
I it is generally unusual to have a lot of text in an app icon: "Prefer including text only when it’s an essential part of your experience or brand" [[Human Interface Guidelines - App Icon](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/)].
I would therefore suggest to crop the icon to only include the blue icon with the antibodies on it as the main app icon. You also don't need to include any corner radius, iOS will crop the icon for you.

We can and should still use the complete branding in e.g. the final presentation as I like the combination of the text and the icon as a bigger picture.

**Comment by PSchmiedmayer** [comment]
@sherryycxie Please also consider updating the app icon at 
[AllergyModules/Sources/AllergyOnboardingFlow/Resources/AppIcon.png](https://github.com/CS342/2023-Allergy/blob/main/AllergyModules/Sources/AllergyOnboardingFlow/Resources/AppIcon.png). Unfortunately we can't easily load the app icon from the main assets and therefore have a duplication there to show it in the onboarding flow for the signup. You might even want to use the icon including the text there if you want to. You can see it being displayed on the sign in and login screens.

**Comment by sherryycxie** [comment]
> 

Just updated the icon in terms of the image itself and updating in the onboarding flow!

**Review by PSchmiedmayer — APPROVED** [review]
Looks great 🚀

**Pull request merged**
