### PR TITLE
feature/sherry

### PR DESCRIPTION
**Pull request by notJustinWu**
# *onboarding*

## :recycle: Current situation & Problem
*there was no working onboarding flow*

## :bulb: Proposed solution
*create an onboarding flow*

## :heavy_plus_sign: Additional Information
*There is still a bug where the "done" button does not exit the survey and go to the onboarding*

### Related PRs
*Reference the related PRs*

### Testing
*Yes tests are included, but they are not working*

### Reviewer Nudging
@PSchmiedmayer 

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [ ] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PSchmiedmayer** [comment]
@navarrae @sonyashijin @rajpabari @sherryycxie Great to see the PR come to life and the changes in this PR! A nice job!

I will take a closer look at the PR tomorrow and inspect the onboarding survey problem.

Nevertheless, here are a few next steps that you can already work on:

1. UI tests: You will have to adjust the UI test to reflect the latest version of the application as detailed in your feature branch. You can do that by modifying the UI tests in the UI tests target of the application. You can run them locally to inspect what is failing and adjust the code accordingly. 

2. The build doesn’t seem to fail due to UI tests but due to a compilation error: https://github.com/CS342/2023-Allergy/actions/runs/4200288555/jobs/7286152367#step:5:1432. Seems like it originates from the image capture functionality that you have in the application.
Looking at the code, it seems like you took it from a more sophisticated implementation. Two comments regarding that:
Please highlight where you got the code from if you copy any code in the license and header information. This is generally a good software development and scientific best practice. We want to give credit where credit is due. Please also highlight this in the PR.
Apple Provides a very simple PhotosPicker API that implements a lot of the photos picker code in the PR that might be more convenient to use and reduces the custom implementation a lot (which is not really needed if we just want the user to select a picture): https://developer.apple.com/documentation/photokit/photospicker
I would suggest removing any unused code or moving the image picture/camera code to a separate PR if you are still working on that. It is generally advised to create small and targeted PRs that focus on a specific modification (also makes the amount of UI and unit tests you have to write smaller).

3. SwiftLint: Please install SwiftLint on your machine and address these errors locally: https://github.com/CS342/2023-Allergy/actions/runs/4200288555/jobs/7286152526. Alternatively, you can look at them in the diff view of GitHub, but I would highly recommend fixing them in Xcode and locally; once you have SwiftLint installed on your machine, the run script in Xcode will automatically display the warnings and errors in your code editor.

4. REUSE: Plenty of files currently don’t conform to the REUSE specification: https://github.com/CS342/2023-Allergy/actions/runs/4200288555/jobs/7286152454. Please ensure that you have the permission and rights to use any code you have there under the MIT license and add an appropriate header. If you copied the code from somewhere, please provide credit and a reference in the header (ideally below the copyright information)

**Review by PSchmiedmayer — CHANGES_REQUESTED** [review]
@navarrae @sonyashijin @rajpabari @sherryycxie Great to see the PR come to life and the changes in this PR! A nice job!

I will take a closer look at the PR tomorrow and inspect the onboarding survey problem.

Nevertheless, here are a few next steps that you can already work on:

1. UI tests: You will have to adjust the UI test to reflect the latest version of the application as detailed in your feature branch. You can do that by modifying the UI tests in the UI tests target of the application. You can run them locally to inspect what is failing and adjust the code accordingly. 

2. The build doesn’t seem to fail due to UI tests but due to a compilation error: https://github.com/CS342/2023-Allergy/actions/runs/4200288555/jobs/7286152367#step:5:1432. Seems like it originates from the image capture functionality that you have in the application.
Looking at the code, it seems like you took it from a more sophisticated implementation. Two comments regarding that:
Please highlight where you got the code from if you copy any code in the license and header information. This is generally a good software development and scientific best practice. We want to give credit where credit is due. Please also highlight this in the PR.
Apple Provides a very simple PhotosPicker API that implements a lot of the photos picker code in the PR that might be more convenient to use and reduces the custom implementation a lot (which is not really needed if we just want the user to select a picture): https://developer.apple.com/documentation/photokit/photospicker
I would suggest removing any unused code or moving the image picture/camera code to a separate PR if you are still working on that. It is generally advised to create small and targeted PRs that focus on a specific modification (also makes the amount of UI and unit tests you have to write smaller).

3. SwiftLint: Please install SwiftLint on your machine and address these errors locally: https://github.com/CS342/2023-Allergy/actions/runs/4200288555/jobs/7286152526. Alternatively, you can look at them in the diff view of GitHub, but I would highly recommend fixing them in Xcode and locally; once you have SwiftLint installed on your machine, the run script in Xcode will automatically display the warnings and errors in your code editor.

4. REUSE: Plenty of files currently don’t conform to the REUSE specification: https://github.com/CS342/2023-Allergy/actions/runs/4200288555/jobs/7286152454. Please ensure that you have the permission and rights to use any code you have there under the MIT license and add an appropriate header. If you copied the code from somewhere, please provide credit and a reference in the header (ideally below the copyright information)

**Comment by PSchmiedmayer** [comment]
@CS342/2023-allergy I have also taken a look at the onboarding survey and would suggest the following: I would suggest moving the survey from the onboarding flow to the home screen of the application.
You can add it as a one-time scheduled task to the schedule view, similar to how we add the example questionnaire to the schedule view.

You can do that in, e.g., the following way using the number of events option in the `AllergySchedule`:
```swift
Task(
    title: String(localized: "...", bundle: .module),
    description: String(localized: "...", bundle: .module),
    schedule: Schedule(
        start: Calendar.current.startOfDay(for: Date()),
        dateComponents: .init(hour: 0, minute: 0), // Every Day at 12:30 AM
        end: .numberOfEvents(1)
    ),
    context: TemplateApplicationTaskContext.questionnaire(Bundle.module.questionnaire(withName: "..."))
)
```

**Review by sonyashijin — APPROVED** [review]
'APPROVE' performed by Xcode.

**Review by sonyashijin — APPROVED** [review]
'APPROVE' performed by Xcode.

**Comment by PSchmiedmayer** [comment]
@navarrae & @CS342/2023-allergy team, do you have any questions or require any help to get this PR merged and all the checks to pass?
Let me know if you need any help with the merge conflict here 👍

**Review by PSchmiedmayer — APPROVED** [review]

**Pull request merged**
