### PR TITLE
Added REUSE for GalleryTab and fixed some swiftlint issues

### PR DESCRIPTION
**Pull request by awangwang**
## :bulb: Proposed solution
Fixed some of the github REUSE and swiftlint checks from PR #16.

### Reviewer Nudging
@PSchmiedmayer there is a force unwrapping violation in line 34 of GalleryLister.swift and I'm not quite sure how to handle it, as optional variables are still pretty new to me. (Removing the ! results in a build error..) Some help or guidance for this issue would be appreciated!

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [ ] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vishnuravi** [comment]
@awangwang you can change the ! to a ? to solve this error.

**Comment by awangwang** [comment]
@vishnuravi changing to a ? gives this build error: For-in loop requires '[StorageReference]?' to conform to 'Sequence'; did you mean to unwrap optional?

**Comment by vishnuravi** [comment]
Sorry, I read the code wrong. You need to unwrap `result` using a guard statement.

Screenshot 2023-03-06 at 1 34 03 PM

**Comment by awangwang** [comment]
Thanks! That took care of it

**Review by sherryycxie — APPROVED** [review]
Approved!

**Pull request merged**
